# Generated by Django 5.0.2 on 2024-04-08 08:18

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, null=True)),
                ("birth_date", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Prefer not to say"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(null=True, upload_to="customer/profile_pics/"),
                ),
                (
                    "user_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Pending", "Pending"),
                            ("Verified", "Verified"),
                        ],
                        default="New",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField(null=True)),
                ("appointment_date", models.DateField()),
                ("day", models.CharField(max_length=9, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        default="New",
                        max_length=255,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="vendors.service",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="customers.customerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_line",
                    models.TextField(
                        help_text="Municipality, Ward No, Tole", max_length=200
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="Nepal", max_length=100)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="customers.customerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField(null=True)),
                (
                    "user_rating",
                    models.IntegerField(validators=[core.validators.validate_rating]),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="customers.appointment",
                    ),
                ),
            ],
        ),
    ]
